import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '@/theme';

export const styles = StyleSheet.create({
  section: {
    backgroundColor: colors.white,
    borderColor: colors.borderLight,
    borderCurve: 'continuous',
    borderRadius: 16,
    borderWidth: 1,
    gap: spacing.lg,
    padding: spacing.md,
    boxShadow: '0 8px 22px rgba(25, 31, 40, 0.06)',
  },
  sectionHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
    minWidth: 0,
  },
  sectionTitleGroup: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold,
    lineHeight: 24,
  },
  sectionSubtitle: {
    color: colors.textTertiary,
    fontSize: typography.fontSize.sm,
    fontVariant: ['tabular-nums'],
    fontWeight: typography.fontWeight.medium,
    lineHeight: 19,
  },
  legendGroup: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    justifyContent: 'flex-end',
    maxWidth: 112,
  },
  legendDot: {
    borderRadius: 999,
    height: 8,
    width: 8,
  },
  legendText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.semibold,
    lineHeight: 16,
  },
  chartRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    minHeight: 210,
  },
  yAxis: {
    justifyContent: 'space-between',
    paddingBottom: 26,
    paddingTop: 20,
    width: 34,
  },
  axisLabel: {
    color: colors.textTertiary,
    fontSize: typography.fontSize.xs,
    fontVariant: ['tabular-nums'],
    fontWeight: typography.fontWeight.semibold,
    lineHeight: 16,
    textAlign: 'right',
  },
  plotArea: {
    flex: 1,
    minWidth: 0,
    position: 'relative',
  },
  gridLine: {
    backgroundColor: colors.borderLight,
    height: StyleSheet.hairlineWidth,
    left: 0,
    position: 'absolute',
    right: 0,
  },
  gridLineTop: {
    top: 22,
  },
  gridLineMiddle: {
    top: 102,
  },
  gridLineBottom: {
    bottom: 27,
  },
  barRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    height: 210,
  },
  barColumn: {
    alignItems: 'center',
    flex: 1,
    gap: spacing.xs,
    minWidth: 0,
  },
  barSlot: {
    alignItems: 'center',
    height: 176,
    justifyContent: 'flex-end',
    minWidth: 0,
    width: '100%',
  },
  barValue: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.xs,
    fontVariant: ['tabular-nums'],
    fontWeight: typography.fontWeight.bold,
    lineHeight: 16,
    marginBottom: spacing.xs,
    textAlign: 'center',
    width: '100%',
  },
  bar: {
    borderCurve: 'continuous',
    borderRadius: 999,
    minHeight: 8,
    width: '78%',
  },
  latestBar: {
    boxShadow: '0 6px 14px rgba(0, 100, 255, 0.24)',
  },
  xAxisLabel: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.bold,
    lineHeight: 16,
    textAlign: 'center',
    width: '100%',
  },
  deltaSection: {
    borderTopColor: colors.borderLight,
    borderTopWidth: StyleSheet.hairlineWidth,
    gap: spacing.sm,
    paddingTop: spacing.md,
  },
  deltaTitle: {
    color: colors.textPrimary,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.bold,
    lineHeight: 19,
  },
  deltaList: {
    gap: spacing.sm,
  },
  deltaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    minHeight: 24,
    minWidth: 0,
  },
  deltaDate: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.xs,
    fontVariant: ['tabular-nums'],
    fontWeight: typography.fontWeight.semibold,
    lineHeight: 16,
    width: 34,
  },
  deltaTrack: {
    backgroundColor: colors.gray100,
    borderCurve: 'continuous',
    borderRadius: 999,
    flex: 1,
    height: 8,
    overflow: 'hidden',
  },
  deltaFill: {
    borderCurve: 'continuous',
    borderRadius: 999,
    height: 8,
  },
  deltaValue: {
    fontSize: typography.fontSize.xs,
    fontVariant: ['tabular-nums'],
    fontWeight: typography.fontWeight.bold,
    lineHeight: 16,
    textAlign: 'right',
    width: 64,
  },
});
