import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '@/theme';

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: colors.backgroundSecondary,
    flex: 1,
    width: '100%',
  },
  content: {
    gap: spacing.lg,
    paddingBottom: spacing.xxl,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.lg,
  },
  wideContent: {
    alignSelf: 'center',
    maxWidth: 760,
    width: '100%',
  },
  hero: {
    backgroundColor: colors.white,
    borderColor: colors.borderLight,
    borderCurve: 'continuous',
    borderRadius: 18,
    borderWidth: 1,
    gap: spacing.xl,
    overflow: 'hidden',
    padding: spacing.lg,
    boxShadow: '0 10px 28px rgba(25, 31, 40, 0.08)',
  },
  heroTop: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
    minWidth: 0,
  },
  heroTitleGroup: {
    flex: 1,
    gap: spacing.xs,
    minWidth: 0,
  },
  eyebrow: {
    color: colors.primary,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.bold,
    lineHeight: 19,
  },
  title: {
    color: colors.textPrimary,
    fontSize: typography.fontSize.xxxl,
    fontWeight: typography.fontWeight.bold,
    lineHeight: 39,
  },
  currentBadge: {
    alignItems: 'flex-end',
    backgroundColor: colors.primaryTint,
    borderColor: 'rgba(0, 100, 255, 0.14)',
    borderCurve: 'continuous',
    borderRadius: 14,
    borderWidth: 1,
    minWidth: 88,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  currentBadgeLabel: {
    color: colors.primary,
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.semibold,
    lineHeight: 16,
  },
  currentBadgeValue: {
    color: colors.primaryDark,
    fontSize: typography.fontSize.xl,
    fontVariant: ['tabular-nums'],
    fontWeight: typography.fontWeight.bold,
    lineHeight: 27,
  },
  heroMetricRow: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderLight,
    borderCurve: 'continuous',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 78,
    overflow: 'hidden',
  },
  heroMetric: {
    flex: 1,
    gap: spacing.xs,
    justifyContent: 'center',
    minWidth: 0,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.md,
  },
  heroMetricLabel: {
    color: colors.textTertiary,
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.semibold,
    lineHeight: 16,
    textAlign: 'center',
  },
  heroMetricValue: {
    color: colors.textPrimary,
    fontSize: typography.fontSize.xl,
    fontVariant: ['tabular-nums'],
    fontWeight: typography.fontWeight.bold,
    lineHeight: 27,
    textAlign: 'center',
  },
  improvedValue: {
    color: colors.success,
  },
  heroDivider: {
    backgroundColor: colors.borderLight,
    width: StyleSheet.hairlineWidth,
  },
  metricGrid: {
    gap: spacing.sm,
  },
  metricRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  summaryPanel: {
    backgroundColor: colors.white,
    borderColor: colors.borderLight,
    borderCurve: 'continuous',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 86,
    overflow: 'hidden',
    boxShadow: '0 8px 22px rgba(25, 31, 40, 0.06)',
  },
  summaryRow: {
    alignItems: 'center',
    flex: 1,
    gap: spacing.xs,
    justifyContent: 'center',
    minWidth: 0,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.md,
  },
  summaryLabel: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.semibold,
    lineHeight: 16,
    textAlign: 'center',
  },
  summaryValue: {
    color: colors.textPrimary,
    fontSize: typography.fontSize.lg,
    fontVariant: ['tabular-nums'],
    fontWeight: typography.fontWeight.bold,
    lineHeight: 24,
    textAlign: 'center',
  },
  summaryDivider: {
    backgroundColor: colors.borderLight,
    width: StyleSheet.hairlineWidth,
  },
});
