export interface DemoSpellCheckExample {
  id: string;
  sentence: string;
  wrongText: string;
  correctText: string;
  reason: string;
}

export const demoSpellCheckExamples: readonly DemoSpellCheckExample[] = [
  {
    id: 'demo-001',
    sentence: '오늘은 시간이 안되요.',
    wrongText: '안되요',
    correctText: '안 돼요',
    reason: "'되어요'의 준말은 '돼요'이고, 부정 표현은 띄어 씁니다.",
  },
  {
    id: 'demo-002',
    sentence: '지금 가도 되요?',
    wrongText: '되요',
    correctText: '돼요',
    reason: "'되어요'를 줄이면 '돼요'가 됩니다.",
  },
  {
    id: 'demo-003',
    sentence: '숙제를 다 했는데도 틀렸다고 됬어요.',
    wrongText: '됬어요',
    correctText: '됐어요',
    reason: "'되었어요'의 준말은 '됐어요'입니다.",
  },
  {
    id: 'demo-004',
    sentence: '내일까지 꼭 보낼께요.',
    wrongText: '보낼께요',
    correctText: '보낼게요',
    reason: "약속이나 의지를 나타낼 때는 '-ㄹ게요'로 씁니다.",
  },
  {
    id: 'demo-005',
    sentence: '생일이 몇일 남았어?',
    wrongText: '몇일',
    correctText: '며칠',
    reason: "날짜를 물을 때의 표준어는 '며칠'입니다.",
  },
  {
    id: 'demo-006',
    sentence: '왠만하면 오늘 끝내자.',
    wrongText: '왠만하면',
    correctText: '웬만하면',
    reason: "'웬만하다'가 바른 표기입니다.",
  },
  {
    id: 'demo-007',
    sentence: '금새 다시 연락할게.',
    wrongText: '금새',
    correctText: '금세',
    reason: "짧은 시간을 뜻할 때는 '금세'로 씁니다.",
  },
  {
    id: 'demo-008',
    sentence: '설겆이는 내가 할게.',
    wrongText: '설겆이',
    correctText: '설거지',
    reason: "표준어는 '설거지'입니다.",
  },
  {
    id: 'demo-009',
    sentence: '내일 다시 뵈요.',
    wrongText: '뵈요',
    correctText: '봬요',
    reason: "'뵈어요'의 준말은 '봬요'입니다.",
  },
  {
    id: 'demo-010',
    sentence: '오랫만에 친구를 만났어.',
    wrongText: '오랫만',
    correctText: '오랜만',
    reason: "시간이 오래 지난 뒤를 뜻할 때는 '오랜만'으로 씁니다.",
  },
  {
    id: 'demo-011',
    sentence: '그 말은 정말 어의없다.',
    wrongText: '어의없다',
    correctText: '어이없다',
    reason: "기가 막히다는 뜻은 '어이없다'로 씁니다.",
  },
  {
    id: 'demo-012',
    sentence: '감기가 빨리 낳았으면 좋겠어.',
    wrongText: '낳았으면',
    correctText: '나았으면',
    reason: "병이 좋아지는 것은 '낫다'를 써서 '나았으면'으로 씁니다.",
  },
  {
    id: 'demo-013',
    sentence: '제 바램은 모두가 건강한 거예요.',
    wrongText: '바램',
    correctText: '바람',
    reason: "소망을 뜻할 때는 '바람'이 바른 표기입니다.",
  },
  {
    id: 'demo-014',
    sentence: '그 예기는 나중에 하자.',
    wrongText: '예기',
    correctText: '얘기',
    reason: "이야기의 준말은 '얘기'입니다.",
  },
  {
    id: 'demo-015',
    sentence: '왠일로 이렇게 일찍 왔어?',
    wrongText: '왠일',
    correctText: '웬일',
    reason: "어찌 된 일을 뜻할 때는 '웬일'로 씁니다.",
  },
  {
    id: 'demo-016',
    sentence: '이제 어떻해 해야 하지?',
    wrongText: '어떻해',
    correctText: '어떡해',
    reason: "'어떻게 해'가 줄어든 말은 '어떡해'입니다.",
  },
  {
    id: 'demo-017',
    sentence: '그건 절대 않되.',
    wrongText: '않되',
    correctText: '안 돼',
    reason: "부정 표현은 '안'을 쓰고, '되어'의 준말은 '돼'입니다.",
  },
  {
    id: 'demo-018',
    sentence: '아직 준비가 않됐어.',
    wrongText: '않됐어',
    correctText: '안 됐어',
    reason: "부정 표현은 '안'을 쓰고 '됐다'는 띄어 씁니다.",
  },
  {
    id: 'demo-019',
    sentence: '요세 날씨가 많이 덥다.',
    wrongText: '요세',
    correctText: '요새',
    reason: "요즘을 뜻하는 말은 '요새'입니다.",
  },
  {
    id: 'demo-020',
    sentence: '그 사람은 참 희안하다.',
    wrongText: '희안하다',
    correctText: '희한하다',
    reason: "드물거나 신기하다는 뜻은 '희한하다'입니다.",
  },
  {
    id: 'demo-021',
    sentence: '곰곰히 생각해 봤어.',
    wrongText: '곰곰히',
    correctText: '곰곰이',
    reason: "반복 부사 뒤에는 '곰곰이'처럼 '-이'가 붙습니다.",
  },
  {
    id: 'demo-022',
    sentence: '방을 깨끗히 치웠다.',
    wrongText: '깨끗히',
    correctText: '깨끗이',
    reason: "'깨끗하다'의 부사는 '깨끗이'입니다.",
  },
  {
    id: 'demo-023',
    sentence: '구지 그렇게 말할 필요는 없어.',
    wrongText: '구지',
    correctText: '굳이',
    reason: "일부러 애써서라는 뜻은 '굳이'입니다.",
  },
  {
    id: 'demo-024',
    sentence: '그건 내 역활이 아니야.',
    wrongText: '역활',
    correctText: '역할',
    reason: "맡은 일을 뜻하는 표준어는 '역할'입니다.",
  },
  {
    id: 'demo-025',
    sentence: '짐을 통채로 옮겼어.',
    wrongText: '통채로',
    correctText: '통째로',
    reason: "나누지 않고 전체를 뜻할 때는 '통째로'입니다.",
  },
  {
    id: 'demo-026',
    sentence: '하마트면 지각할 뻔했어.',
    wrongText: '하마트면',
    correctText: '하마터면',
    reason: "자칫하면의 뜻은 '하마터면'입니다.",
  },
  {
    id: 'demo-027',
    sentence: '일일히 설명하지 않아도 돼.',
    wrongText: '일일히',
    correctText: '일일이',
    reason: "하나하나 빠짐없이의 뜻은 '일일이'입니다.",
  },
  {
    id: 'demo-028',
    sentence: '김치를 오래 담궜다.',
    wrongText: '담궜다',
    correctText: '담갔다',
    reason: "'담그다'의 과거형은 '담갔다'입니다.",
  },
  {
    id: 'demo-029',
    sentence: '문을 잠궜는지 확인해 줘.',
    wrongText: '잠궜는지',
    correctText: '잠갔는지',
    reason: "'잠그다'의 과거형은 '잠갔다'입니다.",
  },
  {
    id: 'demo-030',
    sentence: '뒤치닥거리는 이제 그만하고 싶어.',
    wrongText: '뒤치닥거리',
    correctText: '뒤치다꺼리',
    reason: "남의 일을 뒤에서 보살피는 일은 '뒤치다꺼리'입니다.",
  },
];
